version: '3'

services:
  microservice:
    stdin_open: true
    build:
      context: ./microservices/
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    environment:
      - PORT=${PORT}
      - PUBLIC_PATH=${PUBLIC_PATH}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${PORT}:${PORT}
    restart: always
  monolitico:
    stdin_open: true
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    environment:
      - PORT=${PORT2}
      - PUBLIC_PATH=${PUBLIC_PATH}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${PORT2}:${PORT}
    restart: always
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - microservice
        - monolitico